import os
import psycopg


DATABASE_URL = os.environ.get("NEON_DATABASE_URL")


if not DATABASE_URL:
    raise RuntimeError(
        "NEON_DATABASE_URL is not configured."
    )


conn = psycopg.connect(DATABASE_URL)


tables = [
    "users",
    "transactions",
    "password_resets"
]


for table in tables:

    conn.execute(f"""
        DO $$
        BEGIN

            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = '{table}'
                AND column_name = 'id'
                AND identity_generation IS NOT NULL
            ) THEN

                ALTER TABLE {table}
                ALTER COLUMN id
                ADD GENERATED BY DEFAULT AS IDENTITY;

            END IF;

        END
        $$;
    """)


# Make sure identity sequences continue after
# the IDs that were imported from SQLite.

for table in tables:

    conn.execute(f"""
        SELECT setval(
            pg_get_serial_sequence(
                '{table}',
                'id'
            ),
            COALESCE(
                (SELECT MAX(id) FROM {table}),
                1
            ),
            (
                SELECT COUNT(*) > 0
                FROM {table}
            )
        )
    """)


conn.commit()
conn.close()


print("NEON ID REPAIR: SUCCESS")
print("users.id -> identity")
print("transactions.id -> identity")
print("password_resets.id -> identity")
print("Sequences synchronized.")